### model
model_name_or_path: /root/autodl-fs/Qwen2-7B-Instruct/

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: file_editor_with_tools
template: qwen
cutoff_len: 6144
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /root/autodl-fs/adapter/qwen2-7b/lora/sft/file_editor0821/
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
